//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SellLaptop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class cart_do_hoa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cart_do_hoa()
        {
            this.san_pham = new HashSet<san_pham>();
        }

        [Display(Name ="Nhập tên cart đồ họa:")]
        [Required(ErrorMessage ="HÃY NHẬP THÔNG TIN")]
        public string tencartdohoa { get; set; }


        [Display(Name = "Nhập dung lượng:")]
        [Required(ErrorMessage = "HÃY NHẬP THÔNG TIN")]
        public int? dungluong { get; set; }

        [Display(Name = "Nhập cấu tạo thiết kế cart:")]
        [Required(ErrorMessage = "HÃY NHẬP THÔNG TIN")]
        public string thietke { get; set; }
        public bool an { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<san_pham> san_pham { get; set; }
    }
}
