//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SellLaptop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cpu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cpu()
        {
            this.san_pham = new HashSet<san_pham>();
        }
    
        public string hangsx { get; set; }
        public string congnghe { get; set; }
        public string maloai { get; set; }
        public double tocdo { get; set; }
        public string thongtinbodem { get; set; }
        public Nullable<double> tocdotoida { get; set; }
        public double an { get; set; }
    
        public virtual hang_sx hang_sx { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<san_pham> san_pham { get; set; }
    }
}
