//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SellLaptop.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class cpu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cpu()
        {
            this.san_pham = new HashSet<san_pham>();
        }

        [Display(Name = "Nhập hãng sản xuất:")]
        [Required(ErrorMessage = "HÃY NHẬP THÔNG TIN")]
        public string hangsx { get; set; }
        
        [Display(Name = "Nhập Công nghệ của CPU:")]
        [Required(ErrorMessage = "HÃY NHẬP THÔNG TIN")]
        public string congnghe { get; set; }

        [Display(Name = "Nhập mã loại CPU:")]
        [Required(ErrorMessage = "HÃY NHẬP THÔNG TIN")]
        public string maloai { get; set; }

        [Display(Name = "Nhập tốc độ:")]
        [Required(ErrorMessage = "HÃY NHẬP THÔNG TIN")]
        public double tocdo { get; set; }

        [Display(Name = "Nhập thông tin bộ đệm:")]
        [Required(ErrorMessage = "HÃY NHẬP THÔNG TIN")]
        public string thongtinbodem { get; set; }

        [Display(Name = "Nhập tốc độ CPU tối đa:")]
        public Nullable<double> tocdotoida { get; set; }

        public double an { get; set; }
    
        public virtual hang_sx hang_sx { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<san_pham> san_pham { get; set; }
    }
}
