//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SellLaptop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class danh_gia
    {
        public int masp { get; set; }
        public string khachhang { get; set; }
        public System.DateTime thoigian { get; set; }
        public Nullable<int> diem { get; set; }
        public string noidung { get; set; }
    
        public virtual khach_hang khach_hang { get; set; }
        public virtual san_pham san_pham { get; set; }
    }
}
