//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SellLaptop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class khach_hang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public khach_hang()
        {
            this.danh_gia = new HashSet<danh_gia>();
            this.don_hang = new HashSet<don_hang>();
        }
    
        public string tendn { get; set; }
        public string mk { get; set; }
        public string hoten { get; set; }
        public System.DateTime ngsinh { get; set; }
        public bool gioitinh { get; set; }
        public int sdt { get; set; }
        public string email { get; set; }
        public bool quyen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<danh_gia> danh_gia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<don_hang> don_hang { get; set; }
    }
}
