//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SellLaptop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class o_dia_cung
    {
        public int masp { get; set; }
        public string loaiodia { get; set; }
        public int dungluong { get; set; }
        public bool an { get; set; }
    
        public virtual san_pham san_pham { get; set; }
    }
}
