//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SellLaptop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class san_pham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public san_pham()
        {
            this.anh_sp = new HashSet<anh_sp>();
            this.chi_tiet_don_hang = new HashSet<chi_tiet_don_hang>();
            this.danh_gia = new HashSet<danh_gia>();
            this.o_dia_cung = new HashSet<o_dia_cung>();
        }
    
        public int masp { get; set; }
        public string tensp { get; set; }
        public string tenhangsx { get; set; }
        public int gia { get; set; }
        public string mau { get; set; }
        public string icon { get; set; }
        public string loaicpu { get; set; }
        public int ramdl { get; set; }
        public string ramloai { get; set; }
        public int rambus { get; set; }
        public double kichthuocmh { get; set; }
        public string dophangiai { get; set; }
        public string cnmanhinh { get; set; }
        public bool camung { get; set; }
        public string tencartdohoa { get; set; }
        public string cnamthanh { get; set; }
        public string oquang { get; set; }
        public int sousb { get; set; }
        public bool hdmi { get; set; }
        public bool cartsd { get; set; }
        public string ketnoikhac { get; set; }
        public string chucnangkhac { get; set; }
        public string wifi { get; set; }
        public string lan { get; set; }
        public string btoothver { get; set; }
        public double camera { get; set; }
        public string pin { get; set; }
        public string hdh { get; set; }
        public double khoiluong { get; set; }
        public int dai { get; set; }
        public int rong { get; set; }
        public int day { get; set; }
        public string chatlieu { get; set; }
        public int slcon { get; set; }
        public int luotview { get; set; }
        public bool an { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<anh_sp> anh_sp { get; set; }
        public virtual cart_do_hoa cart_do_hoa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<chi_tiet_don_hang> chi_tiet_don_hang { get; set; }
        public virtual cpu cpu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<danh_gia> danh_gia { get; set; }
        public virtual hang_sx hang_sx { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<o_dia_cung> o_dia_cung { get; set; }
    }
}
