//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SellLaptop.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sellLaptopEntities : DbContext
    {
        public sellLaptopEntities()
            : base("name=sellLaptopEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<anh_sp> anh_sp { get; set; }
        public virtual DbSet<cart_do_hoa> cart_do_hoa { get; set; }
        public virtual DbSet<chi_tiet_don_hang> chi_tiet_don_hang { get; set; }
        public virtual DbSet<cpu> cpus { get; set; }
        public virtual DbSet<danh_gia> danh_gia { get; set; }
        public virtual DbSet<don_hang> don_hang { get; set; }
        public virtual DbSet<hang_sx> hang_sx { get; set; }
        public virtual DbSet<khach_hang> khach_hang { get; set; }
        public virtual DbSet<o_dia_cung> o_dia_cung { get; set; }
        public virtual DbSet<san_pham> san_pham { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
